# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/marisco',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/marisco',
                'lib_path': 'marisco'},
  'syms': {'marisco.core': {'marisco.core.foo': ('core.html#foo', 'marisco/core.py')}}}