# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/utils.ipynb.

# %% auto 0
__all__ = ['has_valid_varname']

# %% ../nbs/api/utils.ipynb 2
from netCDF4 import Dataset
from fastcore.test import test_eq

# %% ../nbs/api/utils.ipynb 4
def has_valid_varname(
    var_names=list,
    cdl_path:str = '../../_data/output/maris-cdl.nc',
):
    "Check that proposed variable names are in MARIS CDL"
    has_valid = True
    with Dataset(cdl_path) as nc:
        for name in var_names.values():
            if name not in nc.variables.keys():
                has_valid = False
                print(f'"{name}" variable name not found in MARIS CDL')
    
    return has_valid
