# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/cli/netcdfy.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../../nbs/cli/netcdfy.ipynb 1
from pathlib import Path
from fastcore.script import *
from ..configs import BASE_PATH
import papermill as pm

# %% ../../nbs/cli/netcdfy.ipynb 2
@call_parse
def main(n:str,     # Noteboook (NetCDF handler) path to execute
        ):
    "Encode MARIS dataset as NetCDF using Jupyter Notebook handlers"
    pm.execute_notebook(n, BASE_PATH / 'tmp' / 'output.ipynb')
