# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/fram_strait.ipynb.

# %% auto #0
__all__ = ['RECORDS', 'status', 'FS_KEYWORDS', 'load_data', 'RenameColsCB', 'ParseDateTimeCB', 'AddDepthCB', 'MeltI129CB',
           'AddDetectionLimitCB', 'AddLabCB', 'FormatStationCB', 'get_attrs', 'encode']

# %% ../../nbs/handlers/fram_strait.ipynb #d541866d
from fastcore.all import *
import pandas as pd
import numpy as np
import requests
import io
import gsw

from ..callbacks import PerGroupCB, Transformer, EncodeTimeCB, SanitizeLonLatCB, RemapCB, AddSampleIDCB
from ..metadata import GlobAttrsFeeder, BboxCB, DepthRangeCB, TimeRangeCB, KeyValuePairCB
from ..encoders import NetCDFEncoder
from ..nc2csv import to_csv
from ..callbacks import get_lut

# %% ../../nbs/handlers/fram_strait.ipynb #585e1b91
RECORDS = {
    "FS2022_i129": {
        "url": "https://zenodo.org/records/20425174/files/FS2022_i129.csv?download=1",
    },
    "FS2022S_i129": {
        "url": "https://zenodo.org/records/20628610/files/FS2022S_data_i129.csv?download=1",
    },
    "FS2023_i129": {
        "url": "https://zenodo.org/records/20448047/files/FS2023_i129.csv?download=1",
    },
    "FS2024_i129": {
        "url": "https://zenodo.org/records/20761705/files/FS2024_i129.csv?download=1",
    },
    "FS2025_i129": {
        "url": "https://zenodo.org/records/20761832/files/FS2025_i129.csv?download=1",
    },
}


status = 'Active'

# %% ../../nbs/handlers/fram_strait.ipynb #87c28ee9
def _normalize(df: pd.DataFrame) -> pd.DataFrame:
    "Align FS records to the canonical Fram Strait raw schema"
    df = df.rename(columns={
        "Latitude": "Latitude_degN",
        "Longitude": "Longitude_degE",
    })
    if "Date" not in df.columns:
        df["Date"] = pd.to_datetime(df[["Year", "Month", "Day"]]).dt.strftime("%Y-%m-%d")
        df = df.drop(columns=["Year", "Month", "Day"])
    for col in ["I129_at_kg", "unc_I129_at_kg"]:
        if col not in df.columns:
            df[col] = np.nan
    return df

# %% ../../nbs/handlers/fram_strait.ipynb #4f8d0cf6
def load_data() -> dict:
    "Fetch Fram Strait CSV records and return one combined SEAWATER DataFrame"
    parts = []

    for record in RECORDS.values():
        resp = requests.get(record["url"], timeout=60)
        resp.raise_for_status()

        df = pd.read_csv(
            io.BytesIO(resp.content),
            encoding="utf-8-sig",
        )
        parts.append(_normalize(df))

    return {"SEAWATER": pd.concat(parts, ignore_index=True)}

# %% ../../nbs/handlers/fram_strait.ipynb #4a497743
class RenameColsCB(PerGroupCB):
    "Map Fram Strait provider columns to MARIS standard names"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.rename(columns={
            "Station": "STATION",
            "Latitude_degN": "LAT",
            "Longitude_degE": "LON",
            "PracticalSalinity": "SAL",
            "Temperature_degC": "TEMP",
            "Sample_ID": "SMP_ID_PROVIDER",
        })

# %% ../../nbs/handlers/fram_strait.ipynb #3a1ff1a6
class ParseDateTimeCB(PerGroupCB):
    "Parse FS collection date into a UTC TIME value"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.assign(
            TIME=pd.to_datetime(df["Date"], format="%Y-%m-%d", utc=True)
        ).drop(columns="Date")


# %% ../../nbs/handlers/fram_strait.ipynb #72bb4f06
class AddDepthCB(PerGroupCB):
    "Compute sampling depth using Thermodynamic Equation of SeaWater 2010 (TEOS-10)"
    def each_grp(self, grp, df, tfm): 
        df["SMP_DEPTH"] = np.round(-gsw.z_from_p(df['Pressure_dbar'], df['LAT']), 1)

# %% ../../nbs/handlers/fram_strait.ipynb #d10a2067
class MeltI129CB(PerGroupCB):
    "Reshape wide I-129 value and uncertainty columns into one row per measurement"
    unit_of = {"at_l": 12, "at_kg": 9}
    def each_grp(self, grp, df, tfm):
        id_cols = [c for c in df.columns if not c.startswith(("I129_", "unc_I129_"))]
        val = pd.melt(
            df, id_vars=id_cols,
            value_vars=["I129_at_l", "I129_at_kg"],
            var_name="_unit", value_name="VALUE"
        )
        unc = pd.melt(
            df, id_vars=id_cols,
            value_vars=["unc_I129_at_l", "unc_I129_at_kg"],
            var_name="_unit", value_name="UNC"
        )
        unc["_unit"] = unc["_unit"].str.removeprefix("unc_I129_")
        val["_unit"] = val["_unit"].str.removeprefix("I129_")
        out = val.merge(unc, on=id_cols + ["_unit"], how="left")
        
        out["UNIT"] = out["_unit"].map(self.unit_of)
        out["NUCLIDE"] = 28
        tfm.dfs[grp] = out.drop(columns="_unit").dropna(subset=["VALUE"])


# %% ../../nbs/handlers/fram_strait.ipynb #6fc1506c
class AddDetectionLimitCB(PerGroupCB):
    "Assign missing Detection Limit column to MARIS 'Detected value: 1' category"
    def each_grp(self, grp, df, tfm): 
        tfm.dfs[grp] = df.assign(DL=1)

# %% ../../nbs/handlers/fram_strait.ipynb #54443923
class AddLabCB(PerGroupCB):
    "Assign LAB MARIS ID for LIP, ETH Zürich"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.assign(LAB=345)

# %% ../../nbs/handlers/fram_strait.ipynb #e00396ee
class FormatStationCB(PerGroupCB):
    "Cast STATION to str for the NetCDF4 string-typed station variable"
    def each_grp(self, grp, df, tfm):
        df["STATION"] = df["STATION"].astype(str)

# %% ../../nbs/handlers/fram_strait.ipynb #5fed230e
FS_KEYWORDS = [
    "Fram Strait","Greenland Sea","I-129","radionuclides","seawater","Arctic Ocean",
]

def get_attrs(tfm):
    "Retrieve global attributes for Fram Strait"
    return GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        KeyValuePairCB("keywords", ", ".join(FS_KEYWORDS)),
        KeyValuePairCB("publisher_postprocess_logs", ", ".join(tfm.logs)),
    ])()

# %% ../../nbs/handlers/fram_strait.ipynb #1784dfc3
def encode(
        dest=None,   # Output NetCDF file path
        src=None,    # Unused; Fram Strait 2025 fetches its data from RECORDS
        **kwargs     # Additional arguments
        ):
    "Fram Strait 2002-2025 Iodine-129 seawater radionuclide data"
    dfs = load_data()
    tfm = Transformer(dfs, cbs=[
        RenameColsCB(),
        ParseDateTimeCB(),
        AddDepthCB(),
        MeltI129CB(),
        AddDetectionLimitCB(),
        AddLabCB(),
        SanitizeLonLatCB(),
        EncodeTimeCB(),
        AddSampleIDCB(col_provider="SMP_ID_PROVIDER"),
        FormatStationCB()
        ])
    tfm()
    encoder = NetCDFEncoder(tfm.dfs, dest_fname=dest,
                            global_attrs=get_attrs(tfm))
    encoder.encode()
