# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/fram_strait.ipynb.

# %% auto #0
__all__ = ['META_COLS', 'ETH_COLS', 'VERA_COLS', 'RAW_COLS', 'RECORDS', 'status', 'MEAS_PAT', 'U238_PPB_TO_AT_KG', 'NUCLIDE_LUT',
           'UNIT_LUT', 'LAB_LUT', 'FS_KEYWORDS', 'load_data', 'RenameColsCB', 'ParseDateTimeCB', 'AddDepthCB',
           'MeltFramStraitCB', 'ConvertU238CB', 'AddDetectionLimitCB', 'FormatStationCB', 'get_attrs', 'encode']

# %% ../../nbs/handlers/fram_strait.ipynb #d541866d
from fastcore.all import *
import pandas as pd
import numpy as np
import requests
import io
import gsw

from ..callbacks import PerGroupCB, Transformer, EncodeTimeCB, SanitizeLonLatCB, RemapCB, AddSampleIDCB, get_lut
from ..metadata import GlobAttrsFeeder, BboxCB, DepthRangeCB, TimeRangeCB, KeyValuePairCB
from ..encoders import NetCDFEncoder
from ..nc2csv import to_csv
from ..callbacks import get_lut

# %% ../../nbs/handlers/fram_strait.ipynb #60e56f06
def _lab_meas(lab: str, stem: str) -> tuple:
    "Value and uncertainty column names for `stem` as measured by `lab`"
    return f'{lab}_{stem}', f'{lab}_unc_{stem}'

# %% ../../nbs/handlers/fram_strait.ipynb #51a1926a
def _prefix_lab_cols(df: pd.DataFrame, lab: str, cols: list) -> pd.DataFrame:
    "Prefix `cols` and their `unc_` twins with `lab_`, recording which lab produced them"
    ren = {c: f'{lab}_{c}' for c in cols} | {f'unc_{c}': f'{lab}_unc_{c}' for c in cols}
    return df.rename(columns=ren)

# %% ../../nbs/handlers/fram_strait.ipynb #51a1926a
def _prefix_lab_cols(df: pd.DataFrame, lab: str, cols: list) -> pd.DataFrame:
    "Prefix `cols` and their `unc_` twins with `lab_`, recording which lab produced them"
    ren = {c: f'{lab}_{c}' for c in cols} | {f'unc_{c}': f'{lab}_unc_{c}' for c in cols}
    return df.rename(columns=ren)

# %% ../../nbs/handlers/fram_strait.ipynb #4401aeb4
def _prefer_vera(df: pd.DataFrame, stem: str) -> pd.DataFrame:
    "Where VERA reported `stem`, clear ETH's measurement (value and unc)"
    (v, vu), (e, eu) = _lab_meas('VERA', stem), _lab_meas('ETH', stem)
    df.loc[df[v].notna(), [e, eu]] = np.nan
    return df

# %% ../../nbs/handlers/fram_strait.ipynb #4401aeb4
def _prefer_vera(df: pd.DataFrame, stem: str) -> pd.DataFrame:
    "Where VERA reported `stem`, clear ETH's measurement (value and unc)"
    (v, vu), (e, eu) = _lab_meas('VERA', stem), _lab_meas('ETH', stem)
    df.loc[df[v].notna(), [e, eu]] = np.nan
    return df

# %% ../../nbs/handlers/fram_strait.ipynb #7da34cea
META_COLS = ['Cruise', 'Station', 'Latitude_degN', 'Longitude_degE', 'Date',
             'Niskin', 'Pressure_dbar', 'PracticalSalinity', 'Temperature_degC', 'Sample_ID']

ETH_COLS = ['ETH_I129_at_l', 'ETH_unc_I129_at_l', 'ETH_I129_at_kg', 'ETH_unc_I129_at_kg',
            'ETH_U236_at_l', 'ETH_unc_U236_at_l', 'ETH_U236_at_kg', 'ETH_unc_U236_at_kg',
            'ETH_U238_ppb', 'ETH_unc_U238_ppb']

VERA_COLS = ['VERA_U236_at_l', 'VERA_unc_U236_at_l', 'VERA_U236_at_kg', 'VERA_unc_U236_at_kg',
             'VERA_U238_ppb', 'VERA_unc_U238_ppb']

RAW_COLS = META_COLS + ETH_COLS + VERA_COLS

# %% ../../nbs/handlers/fram_strait.ipynb #b11ef137
def _normalize_2020_21(df: pd.DataFrame) -> pd.DataFrame:
    "Align FS20/FS21 records (ETH + VERA labs) to the canonical Fram Strait raw schema"
    df = df.drop(columns=[c for c in df.columns if 'U236_U238' in c])
    df = df.rename(columns={
        'Temperature_degC_ctd': 'Temperature_degC',
        'Salinity_ctd':         'PracticalSalinity',
        'Bottle':               'Niskin',
    })
    df = _prefix_lab_cols(df, 'ETH',  ['I129_at_l', 'I129_at_kg'])
    df = _prefix_lab_cols(df, 'VERA', ['U236_at_l', 'U236_at_kg', 'U238_ppb'])
    for stem in ['U236_at_l', 'U236_at_kg', 'U238_ppb']:
        df = _prefer_vera(df, stem)
    df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y').dt.strftime('%Y-%m-%d')
    return df[RAW_COLS]

# %% ../../nbs/handlers/fram_strait.ipynb #b1654be8
def _normalize_2022_25(df: pd.DataFrame) -> pd.DataFrame:
    "Align FS22-25 records (ETH lab only) to the canonical Fram Strait raw schema"
    df = df.rename(columns={'Latitude': 'Latitude_degN', 'Longitude': 'Longitude_degE'})
    if 'Date' not in df.columns:
        df['Date'] = pd.to_datetime(df[['Year', 'Month', 'Day']]).dt.strftime('%Y-%m-%d')
    df = _prefix_lab_cols(df, 'ETH', ['I129_at_l', 'I129_at_kg'])
    return df.reindex(columns=RAW_COLS)

# %% ../../nbs/handlers/fram_strait.ipynb #585e1b91
RECORDS = {
    "FS2020_21": {
        "url": "https://zenodo.org/records/19387002/files/FramStrait_2020_2021_radionuclides.csv?download=1",
        "adapter": _normalize_2020_21
    },
    "FS2022_i129": {
        "url": "https://zenodo.org/records/20425174/files/FS2022_i129.csv?download=1",
        "adapter": _normalize_2022_25
    },
    "FS2022S_i129": {
        "url": "https://zenodo.org/records/20628610/files/FS2022S_data_i129.csv?download=1",
        "adapter": _normalize_2022_25
    },
    "FS2023_i129": {
        "url": "https://zenodo.org/records/20448047/files/FS2023_i129.csv?download=1",
        "adapter": _normalize_2022_25
    },
    "FS2024_i129": {
        "url": "https://zenodo.org/records/20761705/files/FS2024_i129.csv?download=1",
        "adapter": _normalize_2022_25
    },
    "FS2025_i129": {
        "url": "https://zenodo.org/records/20761832/files/FS2025_i129.csv?download=1",
        "adapter": _normalize_2022_25
    },
}


status = 'Active'

# %% ../../nbs/handlers/fram_strait.ipynb #2766bbff
def load_data() -> dict:
    "Fetch Fram Strait CSV records and return one combined SEAWATER DataFrame"
    parts = []
    for rec in RECORDS.values():
        resp = requests.get(rec["url"], timeout=60)
        resp.raise_for_status()
        df = pd.read_csv(io.BytesIO(resp.content), encoding="utf-8-sig")
        parts.append(rec["adapter"](df))
    return {"SEAWATER": pd.concat(parts, ignore_index=True)}


# %% ../../nbs/handlers/fram_strait.ipynb #4a497743
class RenameColsCB(PerGroupCB):
    "Map Fram Strait provider columns to MARIS standard names"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.rename(columns={
            "Station": "STATION",
            "Latitude_degN": "LAT",
            "Longitude_degE": "LON",
            "PracticalSalinity": "SAL",
            "Temperature_degC": "TEMP",
            "Sample_ID": "SMP_ID_PROVIDER",
        })

# %% ../../nbs/handlers/fram_strait.ipynb #3a1ff1a6
class ParseDateTimeCB(PerGroupCB):
    "Parse FS collection date into a UTC TIME value"
    def each_grp(self, grp, df, tfm):
        tfm.dfs[grp] = df.assign(
            TIME=pd.to_datetime(df["Date"], format="%Y-%m-%d", utc=True)
        ).drop(columns="Date")


# %% ../../nbs/handlers/fram_strait.ipynb #72bb4f06
class AddDepthCB(PerGroupCB):
    "Compute sampling depth using Thermodynamic Equation of SeaWater 2010 (TEOS-10)"
    def each_grp(self, grp, df, tfm): 
        df["SMP_DEPTH"] = np.round(-gsw.z_from_p(df['Pressure_dbar'], df['LAT']), 1)

# %% ../../nbs/handlers/fram_strait.ipynb #2305f2c6
MEAS_PAT = re.compile(r'^(?P<LAB>[A-Z]+)_(?:(?P<UNC>unc)_)?(?P<NUCLIDE>[A-Za-z]+\d+)_(?P<UNIT>.+)$')

# %% ../../nbs/handlers/fram_strait.ipynb #1642d2c3
class MeltFramStraitCB(PerGroupCB):
    "Reshape wide Fram Strait value and uncertainty columns into one row per measurement"
    def each_grp(self, grp, df, tfm):
        meas = [c for c in df.columns if MEAS_PAT.fullmatch(c)]
        id_cols = [c for c in df.columns if c not in meas]
        long = df.melt(id_vars=id_cols, var_name='_col', value_name='VALUE')
        long[['LAB', 'UNC', 'NUCLIDE', 'UNIT']] = long['_col'].str.extract(MEAS_PAT)
        long['UNC'] = long['UNC'].fillna('val')
        out = long.pivot(index=id_cols + ['LAB', 'NUCLIDE', 'UNIT'], columns='UNC', values='VALUE')
        out = out.reset_index().rename(columns={'val': 'VALUE', 'unc': 'UNC'})
        out.columns.name = None
        tfm.dfs[grp] = out.dropna(subset=['VALUE'])

# %% ../../nbs/handlers/fram_strait.ipynb #158b4dee
# Convert U-238 from ppb to atoms/kg: ppb * 1e-9 * 1000 * (1/238.05) * 6.02214076e23
U238_PPB_TO_AT_KG = 2.529_780e15

# %% ../../nbs/handlers/fram_strait.ipynb #efe7c80e
class ConvertU238CB(PerGroupCB):
    "Convert U-238 VALUE from ppb to atoms/kg"
    def each_grp(self, grp, df, tfm):
        m = df['NUCLIDE'] == 'U238'
        df.loc[m, 'VALUE'] *= U238_PPB_TO_AT_KG
        df.loc[m, 'UNC'] *= U238_PPB_TO_AT_KG
        df.loc[m, 'UNIT'] = 'at_kg'

# %% ../../nbs/handlers/fram_strait.ipynb #61385778
# MARIS nuclide IDs confirmed via get_lut('NUCLIDE')
NUCLIDE_LUT = {'I129': 28, 'U236': 108, 'U238': 64}

# MARIS unit IDs confirmed via get_lut('UNIT')
UNIT_LUT = {'at_kg': 9, 'at_l': 12}

# MARIS unit IDs confirmed via get_lut('LAB')
LAB_LUT = {'ETH': 345, 'VERA': 504}


# %% ../../nbs/handlers/fram_strait.ipynb #6fc1506c
class AddDetectionLimitCB(PerGroupCB):
    "Assign missing Detection Limit column to MARIS 'Detected value: 1' category"
    def each_grp(self, grp, df, tfm): 
        tfm.dfs[grp] = df.assign(DL=1)

# %% ../../nbs/handlers/fram_strait.ipynb #e00396ee
class FormatStationCB(PerGroupCB):
    "Cast STATION to str for the NetCDF4 string-typed station variable"
    def each_grp(self, grp, df, tfm):
        df["STATION"] = df["STATION"].astype(str)

# %% ../../nbs/handlers/fram_strait.ipynb #5fed230e
FS_KEYWORDS = [
    "Fram Strait","Greenland Sea","I-129","U-236","U-238","radionuclides","seawater","Arctic Ocean",
]

def get_attrs(tfm):
    "Retrieve global attributes for Fram Strait"
    return GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        KeyValuePairCB("keywords", ", ".join(FS_KEYWORDS)),
        KeyValuePairCB("publisher_postprocess_logs", ", ".join(tfm.logs)),
    ])()

# %% ../../nbs/handlers/fram_strait.ipynb #1784dfc3
def encode(
        dest=None,   # Output NetCDF file path
        src=None,    # Unused; Fram Strait fetches its data from RECORDS
        **kwargs     # Additional arguments
        ):
    "Fram Strait 2020-2025 I-129, U-236, U-238 seawater radionuclide data"
    dfs = load_data()
    tfm = Transformer(dfs, cbs=[
        RenameColsCB(),
        ParseDateTimeCB(),
        AddDepthCB(),
        MeltFramStraitCB(),
        ConvertU238CB(),
        RemapCB(lut=NUCLIDE_LUT, col_remap='NUCLIDE', col_src='NUCLIDE'),
        RemapCB(lut=UNIT_LUT, col_remap='UNIT', col_src='UNIT'),
        RemapCB(lut=LAB_LUT, col_remap='LAB', col_src='LAB'),
        AddDetectionLimitCB(),
        SanitizeLonLatCB(),
        EncodeTimeCB(),
        AddSampleIDCB(col_provider="SMP_ID_PROVIDER"),
        FormatStationCB()
        ])
    tfm()
    encoder = NetCDFEncoder(tfm.dfs, dest_fname=dest,
                            global_attrs=get_attrs(tfm))
    encoder.encode()
