"""Docs: https://franckalbinet.github.io/mariscohandlers/geotraces.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/geotraces.ipynb.

# %% auto #0
__all__ = ['fname_in', 'fname_out', 'zotero_key', 'load_data', 'common_coi', 'nuclides_pattern', 'phase', 'smp_method',
           'nuclides_name', 'units_lut', 'renaming_rules', 'lut_nuclides', 'kw', 'SelectColsOfInterestCB',
           'WideToLongCB', 'ExtractUnitCB', 'ExtractFilteringStatusCB', 'ExtractSamplingMethodCB', 'RenameNuclideCB',
           'StandardizeUnitCB', 'RenameColumnCB', 'UnshiftLongitudeCB', 'DispatchToGroupCB', 'AddSampleIDCB',
           'get_attrs', 'encode']

# %% ../../nbs/handlers/geotraces.ipynb #3a8d979f
from fastcore.all import *
import pandas as pd
import numpy as np
import re

from marisco.callbacks import (
    Callback, 
    PerGroupCB,
    Transformer, 
    ParseTimeCB,
    SanitizeLonLatCB, 
    EncodeTimeCB,
    RemapCB
)

from marisco.metadata import (
    GlobAttrsFeeder, 
    BboxCB,
    DepthRangeCB, 
    TimeRangeCB,
    ZoteroCB,
    KeyValuePairCB
)

from ..configs import AVOGADRO, get_lut, lut_path
from ..encoders import NetCDFEncoder
from ..nc2csv import to_csv

# %% ../../nbs/handlers/geotraces.ipynb #d02bf0a9
fname_in = '../../_data/geotraces/GEOTRACES_IDP2021_v2/seawater/ascii/GEOTRACES_IDP2021_Seawater_Discrete_Sample_Data_v2.csv'
fname_out = '../../_data/output/190-geotraces-2021.nc'
zotero_key = '97UIMEXN'

# %% ../../nbs/handlers/geotraces.ipynb #70d6efc1
load_data = lambda fname: pd.read_csv(fname_in)

# %% ../../nbs/handlers/geotraces.ipynb #8d3a7bba-39d7-4fc3-8f0e-fb83ff52dcc2
# Metadata columns always kept as identifiers when reshaping wide → long
common_coi = ['yyyy-mm-ddThh:mm:ss.sss', 'Longitude [degrees_east]',
              'Latitude [degrees_north]', 'Bot. Depth [m]', 'DEPTH [m]', 'BODC Bottle Number:INTEGER']

# Regex patterns identifying radionuclide measurement columns
nuclides_pattern = ['^TRITI', '^Th_228', '^Th_23[024]', '^Pa_231', 
                    '^U_236_[DT]', '^Be_', '^Cs_137', '^Pb_210', '^Po_210',
                    '^Ra_22[3468]', '^Np_237', '^Pu_239_[D]', '^Pu_240', '^Pu_239_Pu_240',
                    '^I_129', '^Ac_227']  

# %% ../../nbs/handlers/geotraces.ipynb #fa7ae0ca
class SelectColsOfInterestCB(Callback):
    "Select columns of interest from the wide Geotraces dataframe."
    def __init__(self,
                 common_coi: list,       # Non-nuclide columns always kept as id_vars
                 nuclides_pattern: list  # Regex patterns matching nuclide column names
                 ): store_attr()
    def __call__(self, tfm):
        nuc_of_interest = [c for c in tfm.df.columns if 
                           any(re.match(pattern, c) for pattern in self.nuclides_pattern)]
        tfm.df = tfm.df[self.common_coi + nuc_of_interest]

# %% ../../nbs/handlers/geotraces.ipynb #b060bb07-5565-4928-8b43-4abc5e64eb97
class WideToLongCB(Callback):
    "Reshape wide nuclide columns to long format so unit, method, and filter status can be extracted from column names."
    def __init__(self,
                 common_coi: list,         # Non-nuclide columns kept as id_vars in melt
                 nuclides_pattern: list,   # Regex patterns identifying nuclide columns
                 var_name: str='NUCLIDE',  # Output column name for nuclide identifiers
                 value_name: str='VALUE',  # Output column name for measurement values
                 ): 
        store_attr()
        
    def __call__(self, tfm):
        nuc_of_interest = [c for c in tfm.df.columns if 
                           any(re.match(pattern, c) for pattern in self.nuclides_pattern)]
        tfm.df = pd.melt(tfm.df, id_vars=self.common_coi, value_vars=nuc_of_interest, 
                          var_name=self.var_name, value_name=self.value_name)
        tfm.df.dropna(subset=self.value_name, inplace=True)

# %% ../../nbs/handlers/geotraces.ipynb #3e982489-7c69-4b6d-9930-8f786220ad5b
class ExtractUnitCB(Callback):
    "Extract measurement unit from nuclide column names (e.g. 'Cs_137_D_CONC_BOTTLE [uBq/kg]' → 'uBq/kg')."
    def __init__(self,
                 var_name: str='NUCLIDE'  # Column containing nuclide names with embedded units in brackets
                 ): 
        store_attr()
        self.unit_col_name = 'UNIT'

    def extract_unit(self, s):
        match = re.search(r'\[(.*?)\]', s)
        return match.group(1) if match else None
        
    def __call__(self, tfm):
        tfm.df[self.unit_col_name] = tfm.df[self.var_name].apply(self.extract_unit)

# %% ../../nbs/handlers/geotraces.ipynb #efb9477e-f593-4d15-b8b8-c073bd6bb590
# Phase code embedded in column names → FILT status and sample type group
phase = {
    'D': {'FILT': 1, 'group': 'SEAWATER'},
    'T': {'FILT': 2, 'group': 'SEAWATER'},
    'TP': {'FILT': 1, 'group': 'SUSPENDED_MATTER'}, 
    'LPT': {'FILT': 1, 'group': 'SUSPENDED_MATTER'},
    'SPT': {'FILT': 1, 'group': 'SUSPENDED_MATTER'}}

# %% ../../nbs/handlers/geotraces.ipynb #3ba72b3a-a013-4b5d-881a-9fd0a7e8b74c
class ExtractFilteringStatusCB(Callback):
    "Extract filtering status and sample-type group from nuclide column names using phase code (e.g. _D_, _T_, _TP_)."
    def __init__(self,
                 phase: dict,              # Phase code → {FILT, group} mapping (e.g. {'D': {'FILT': 1, 'group': 'SEAWATER'}})
                 var_name: str='NUCLIDE'   # Column containing nuclide names with embedded phase codes
                 ): 
        store_attr()
        self.filt_col_name = 'FILT'

    def extract_filt_status(self, s):
        matched_string = self.match(s)
        return self.phase[matched_string.group(1)][self.filt_col_name] if matched_string else None

    def match(self, s):
        return re.search(r'_(' + '|'.join(self.phase.keys()) + ')_', s)
        
    def extract_group(self, s):
        matched_string = self.match(s)
        return self.phase[matched_string.group(1)]['group'] if matched_string else None
        
    def __call__(self, tfm):
        tfm.df[self.filt_col_name] = tfm.df[self.var_name].apply(self.extract_filt_status)
        tfm.df['GROUP'] = tfm.df[self.var_name].apply(self.extract_group)

# %% ../../nbs/handlers/geotraces.ipynb #e7c79502-f09e-49c0-851b-cdb2eca82eac
# Sampling method code → MARIS method ID mapping (to be validated)
smp_method = {
    'BOTTLE': 1,
    'FISH': 18,
    'PUMP': 14,
    'UWAY': 24}

# %% ../../nbs/handlers/geotraces.ipynb #3b4663f8-6cb1-45c3-8437-97a6ba9c5214
class ExtractSamplingMethodCB(Callback):
    "Extract sampling method from nuclide names."
    def __init__(self, 
                 smp_method:dict = smp_method, # Sampling method lookup table
                 var_name='NUCLIDE',            # Column name containing nuclide names
                 smp_method_col_name = 'SAMP_MET' # Column name for sampling method in output df
                 ): 
        store_attr()

    def extract_smp_method(self, s):
        match = re.search(r'_(' + '|'.join(self.smp_method.keys()) + ') ', s)
        return self.smp_method[match.group(1)] if match else None
        
    def __call__(self, tfm):
        tfm.df[self.smp_method_col_name] = tfm.df[self.var_name].apply(self.extract_smp_method)

# %% ../../nbs/handlers/geotraces.ipynb #8eb5c23c-8930-4100-b9bc-d536d2b8d3b6
# Provider-specific nuclide name overrides for MARIS standardisation
nuclides_name = {'TRITIUM': 'h3', 'Pu_239_Pu_240': 'pu239_240_tot'}

# %% ../../nbs/handlers/geotraces.ipynb #06cc02db-47e0-4fe9-8586-d76bcb5c4615
class RenameNuclideCB(Callback):
    "Remap nuclides name to MARIS standard."
    def __init__(self,
                 nuclides_name: dict,     # Provider-specific name overrides e.g. {'TRITIUM': 'h3'}
                 var_name: str='NUCLIDE'  # Column containing nuclide names to standardize
                 ): 
        store_attr()
        self.patterns = ['_D', '_T', '_TP', '_LPT', '_SPT']

    def extract_nuclide_name(self, s):
        match = re.search(r'(.*?)(' + '|'.join(self.patterns) + ')', s)
        return match.group(1) if match else None

    def standardize_name(self, s):
        s = self.extract_nuclide_name(s)
        return self.nuclides_name[s] if s in self.nuclides_name else s.lower().replace('_', '')
        
    def __call__(self, tfm):
        tfm.df[self.var_name] = tfm.df[self.var_name].apply(self.standardize_name)

# %% ../../nbs/handlers/geotraces.ipynb #80145187-bb90-4428-9d31-77a82ec916b4
# Geotraces unit → MARIS unit ID and conversion factor mapping
units_lut = {
    'TU': {'id': 7, 'factor': 1},
    'uBq/kg': {'id': 3, 'factor': 1e-6},
    'atoms/kg': {'id': 9, 'factor': 1},
    'mBq/kg': {'id': 3, 'factor': 1e-3},
    'pmol/kg': {'id': 9, 'factor': 1e-12 * AVOGADRO}
    }

# %% ../../nbs/handlers/geotraces.ipynb #070abb88-c987-4eec-b0dc-7b69a61c0093
class StandardizeUnitCB(Callback):
    "Remap Geotraces unit strings to MARIS unit IDs, rescaling measurement values by the appropriate conversion factor where units share a common MARIS unit ID (e.g. uBq/kg and mBq/kg both map to ID 3 but differ 1000x)."
    def __init__(self, 
                 units_lut: dict,              # Unit string → {id, factor} conversion mapping
                 unit_col_name: str='UNIT',    # Column containing unit strings to remap
                 var_name: str='VALUE'         # Column containing measurement values to rescale
                 ): 
        store_attr()
        
    def __call__(self, tfm):
        # Convert/rescale values
        tfm.df[self.var_name] *= tfm.df[self.unit_col_name].map(
            {k: v['factor'] for k, v in self.units_lut.items()})
        
        # Match MARIS unit id
        tfm.df[self.unit_col_name] = tfm.df[self.unit_col_name].map(
            {k: v['id'] for k, v in self.units_lut.items()})

# %% ../../nbs/handlers/geotraces.ipynb #8896686b
# Geotraces column name → MARIS standard name mapping
renaming_rules = {
    'yyyy-mm-ddThh:mm:ss.sss': 'TIME',
    'Longitude [degrees_east]': 'LON',
    'Latitude [degrees_north]': 'LAT',
    'DEPTH [m]': 'SMP_DEPTH',
    'Bot. Depth [m]': 'TOT_DEPTH',
    'BODC Bottle Number:INTEGER': 'SMP_ID_PROVIDER'
}

# %% ../../nbs/handlers/geotraces.ipynb #5a1b1521-a4d4-4839-a2c1-444c31332ef2
class RenameColumnCB(Callback):
    "Remap Geotraces-specific coordinate, depth, and sample-ID column names to MARIS standard nomenclature."
    def __init__(self,
                 lut: dict=renaming_rules  # Provider column name → MARIS standard name mapping
                 ): store_attr()
    def __call__(self, tfm):
        new_col_names = [self.lut[name] if name in self.lut else name for name in tfm.df.columns]
        tfm.df.columns = new_col_names

# %% ../../nbs/handlers/geotraces.ipynb #ee266cb0-ad2f-4548-b68b-80d0f33ef403
class UnshiftLongitudeCB(Callback):
    "Shift longitudes from Geotraces [0, 360] convention to MARIS [-180, 180] by subtracting 180."
    def __init__(self,
                 lon_col_name: str='LON'  # Column containing longitudes in [0, 360] to shift
                 ): 
        store_attr()
    def __call__(self, tfm):
        tfm.df[self.lon_col_name] = tfm.df[self.lon_col_name] - 180

# %% ../../nbs/handlers/geotraces.ipynb #347a0371-c6e4-4b7d-b1f8-8ffb00509e42
class DispatchToGroupCB(Callback):
    "Split flat dataframe into per-group dict keyed by sample type (SEAWATER, SUSPENDED_MATTER, …)."
    def __init__(self,
                 group_name: str='GROUP'  # Column whose distinct values become the output dict keys
                 ): 
        store_attr()
        
    def __call__(self, tfm):
        tfm.dfs = dict(tuple(tfm.df.groupby(self.group_name)))
        for key in tfm.dfs:
            tfm.dfs[key] = tfm.dfs[key].drop(self.group_name, axis=1)

# %% ../../nbs/handlers/geotraces.ipynb #6da45d74
class AddSampleIDCB(PerGroupCB):
    "Assign a sequential SMP_ID per sample-type group; cast SMP_ID_PROVIDER (BODC Bottle Number) to string for NetCDF VLEN compatibility."
    def each_grp(self,
                 grp: str,          # Group key e.g. 'SEAWATER', 'SUSPENDED_MATTER'
                 df: pd.DataFrame,  # DataFrame for this group
                 tfm,               # Parent Transformer
                 ):
        df['SMP_ID'] = range(1, len(df) + 1)
        df['SMP_ID_PROVIDER'] = df['SMP_ID_PROVIDER'].astype(str)

# %% ../../nbs/handlers/geotraces.ipynb #57f34e80
# Lookup table: MARIS nc_name → nuclide_id
lut_nuclides = lambda: get_lut('NUCLIDE', reverse=False)

# %% ../../nbs/handlers/geotraces.ipynb #f98fd736
kw = ['oceanography', 'Earth Science > Oceans > Ocean Chemistry> Radionuclides',
      'Earth Science > Human Dimensions > Environmental Impacts > Nuclear Radiation Exposure',
      'Earth Science > Oceans > Ocean Chemistry > Ocean Tracers, Earth Science > Oceans > Marine Sediments',
      'Earth Science > Oceans > Ocean Chemistry, Earth Science > Oceans > Sea Ice > Isotopes',
      'Earth Science > Oceans > Water Quality > Ocean Contaminants',
      'Earth Science > Biological Classification > Animals/Vertebrates > Fish',
      'Earth Science > Biosphere > Ecosystems > Marine Ecosystems',
      'Earth Science > Biological Classification > Animals/Invertebrates > Mollusks',
      'Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans',
      'Earth Science > Biological Classification > Plants > Macroalgae (Seaweeds)']

# %% ../../nbs/handlers/geotraces.ipynb #ca5357b7
def get_attrs(
        tfm, 
        zotero_key, 
        kw=kw
        ):
    "Retrieve global attributes from Geotraces dataset."
    return GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        ZoteroCB(zotero_key),
        KeyValuePairCB('keywords', ', '.join(kw)),
        KeyValuePairCB('publisher_postprocess_logs', ', '.join(tfm.logs))
        ])()

# %% ../../nbs/handlers/geotraces.ipynb #d591d3f2-8843-4dad-9514-d7e2d77af592
def encode(
        fname_in:str,    # Path to the raw Geotraces input CSV (the IDP2021 discrete sample data)
        fname_out:str,   # Destination path for the NetCDF4 output file
        **kwargs         # Pass verbose=True for detailed NetCDFEncoder output
        ):
    "Orchestrate the full Geotraces curation pipeline: load, transform, and encode to MARIS NetCDF4 format."
    df = pd.read_csv(fname_in)
    tfm = Transformer(df, cbs=[
        SelectColsOfInterestCB(common_coi, nuclides_pattern),
        WideToLongCB(common_coi, nuclides_pattern),
        ExtractUnitCB(),
        ExtractFilteringStatusCB(phase),
        ExtractSamplingMethodCB(smp_method),
        RenameNuclideCB(nuclides_name),
        StandardizeUnitCB(units_lut),
        RenameColumnCB(renaming_rules),
        UnshiftLongitudeCB(),
        DispatchToGroupCB(),
        AddSampleIDCB(),
        ParseTimeCB(),
        EncodeTimeCB(),
        SanitizeLonLatCB(),
        RemapCB(fn_lut=lut_nuclides, col_remap='NUCLIDE', col_src='NUCLIDE')
        ])
    
    tfm()
    encoder = NetCDFEncoder(tfm.dfs, 
                            dest_fname=fname_out,    
                            global_attrs=get_attrs(tfm, zotero_key=zotero_key, kw=kw),
                            verbose=kwargs.get('verbose', False)
                           )
    encoder.encode()

