"""Docs: https://franckalbinet.github.io/marisco/handlers/ospar.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/ospar.ipynb.

# %% auto #0
__all__ = ['src_dir', 'fname_out', 'zotero_key', 'status', 'encode']

# %% ../../nbs/handlers/ospar.ipynb #715e849d
src_dir = 'https://raw.githubusercontent.com/franckalbinet/maris-crawlers/refs/heads/main/data/processed/OSPAR'
fname_out = '../../_data/output/191-OSPAR-2024.nc'
zotero_key ='LQRA4MMK' # OSPAR MORS zotero key

status = 'Under refactoring'

# %% ../../nbs/handlers/ospar.ipynb #b0abbbd8
def encode(
    dest: str, # Output file name
    src: str = None, # Path to raw <PROVIDER> data
    **kwargs # Additional arguments
    ) -> None:
    "OSPAR data"
    assert False, "OSPAR is under refactoring; encode() is not yet implemented"
