# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/handlers/tepco.ipynb.

# %% auto 0
__all__ = ['load_data', 'FixMissingValuesCB']

# %% ../../nbs/handlers/tepco.ipynb 7
def load_data(fname_in):
    "Load TEPCO seawater data"
    
    # get measurements
    df_meas = pd.read_excel(fname_in, 
                            skiprows=1, nrows=23643,
                            converters={'Sampling time': lambda x: x if x != '' else '00:00:00'})
    # get locations
    df_loc = pd.read_excel(fname_in, skiprows=23647, nrows=48, usecols=[0,1,2])
    # join
    df = pd.merge(df_meas, df_loc, how="inner", on='Sampling point number')
    df.drop(columns=['Sampling point number'], inplace=True)
    df.index.name = 'sample'
    return df

# %% ../../nbs/handlers/tepco.ipynb 15
class FixMissingValuesCB(Callback):
    "Assign `NaN` to values equal to `ND` (not detected) - to be confirmed "

    def __call__(self, tfm): 
        tfm.df[tfm.df == 'ND'] = np.nan
