project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 6
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: arrow
    grid:
      sidebar-width: 180px
      body-width: 980px
      margin-width: 300px
      gutter-width: 1.0rem

website:
  title: "marisco"
  site-url: "https://franckalbinet.github.io/marisco"
  description: "MARIS companion package and tutorials"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/franckalbinet/marisco"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/franckalbinet/marisco"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
