"""Docs: https://franckalbinet.github.io/mariscohandlers/pipeline/writer.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/handlers/pipeline/writer.ipynb.

# %% ../../../nbs/handlers/pipeline/writer.ipynb #21a89f69
from __future__ import annotations
from marisco.handlers.pipeline.output import (
    _SimpleBboxCB,
    build_global_attrs,
    project_netcdf_columns,
    validate_required_columns,
    write_netcdf,
)


# %% auto #0
__all__ = []

# %% ../../../nbs/handlers/pipeline/writer.ipynb #04ca11cb
from marisco.handlers.pipeline.output import (
    _SimpleBboxCB,
    build_global_attrs,
    project_netcdf_columns,
    validate_required_columns,
    write_netcdf,
)

