placeholder = "_to_be_filled_in_"

[grps.sea]
name = "seawater"

[grps.bio]
name = "biota"

[grps.sed]
name = "sediment"

[grps.sus]
name = "suspended-matter"

[global_attrs]
id = ""
title = ""
summary = ""
keywords = ""
keywords_vocabulary = "GCMD Science Keywords"
keywords_vocabulary_url = "https://gcmd.earthdata.nasa.gov/static/kms/"
record = ""
featureType = ""
cdm_data_type = ""
Conventions = "CF-1.10 ACDD-1.3"
publisher_name = "Paul MCGINNITY, Iolanda OSVATH, Florence DESCROIX-COMANDUCCI"
publisher_email = "p.mc-ginnity@iaea.org, i.osvath@iaea.org, F.Descroix-Comanducci@iaea.org"
publisher_url = "https://maris.iaea.org"
publisher_institution = "International Atomic Energy Agency - IAEA"
creator_name = ""
institution = ""
metadata_link = ""
creator_email = ""
creator_url = ""
references = ""
license = "Without prejudice to the applicable Terms and Conditions (https://nucleus.iaea.org/Pages/Others/Disclaimer.aspx), I hereby agree that any use of the data will contain appropriate acknowledgement of the data source(s) and the IAEA Marine Radioactivity Information System (MARIS)."
comment = ""
geospatial_lat_min = ""
geospatial_lon_min = ""
geospatial_lat_max = ""
geospatial_lon_max = ""
geospatial_vertical_min = ""
geospatial_vertical_max = ""
geospatial_bounds = ""
geospatial_bounds_crs = "EPSG:4326"
time_coverage_start = ""
time_coverage_end = ""
local_time_zone = ""
date_created = ""
date_modified = ""
publisher_postprocess_logs = ""

[dim]
name = "sample"
dtype = "u8"

[dim.attrs]
long_name = "Sample ID of measurement"

[vars.defaults.lon]
name = "lon"
dtype = "f4"

[vars.defaults.lon.attrs]
long_name = "Measurement longitude"
standard_name = "longitude"
units = "degrees_north"
axis = "Y"
_CoordinateAxisType = "Lon"

[vars.defaults.lat]
name = "lat"
dtype = "f4"

[vars.defaults.lat.attrs]
long_name = "Measurement latitude"
standard_name = "latitude"
units = "degrees_east"
axis = "X"
_CoordinateAxisType = "Lat"

[vars.defaults.depth]
name = "depth"
dtype = "f4"

[vars.defaults.depth.attrs]
long_name = "Depth below seal level"
standard_name = "depth_below_sea_floor"
units = "m"
axis = "Z"

[vars.defaults.time]
name = "time"
dtype = "u8"

[vars.defaults.time.attrs]
long_name = "Time of measurement"
standard_name = "time"
units = "seconds since 1970-01-01 00:00:00.0"
time_origin = "1970-01-01 00:00:00"
time_zone = "UTC"
abbreviation = "Date/Time"
axis = "T"
calendar = "gregorian"

[vars.bio.bio_group]
name = "bio_group"
dtype = "bio_group_t"

[vars.bio.bio_group.attrs]
long_name = "Biota group"
standard_name = "biota_group_tbd"

[vars.bio.species_id]
name = "species_id"
dtype = "species_t"

[vars.bio.species_id.attrs]
long_name = "Species ID"
standard_name = "AphiaID"

[vars.bio.body_part]
name = "body_part"
dtype = "body_part_t"

[vars.bio.body_part.attrs]
long_name = "Body part"
standard_name = "body_part_tbd"

[vars.sed.sed_type]
name = "sed_type"
dtype = "sed_type_t"

[vars.sed.sed_type.attrs]
long_name = "Sediment type"
standard_name = "sediment_type_tbd"

[vars.suffixes.uncertainty]
name = "_unc"
dtype = "f4"

[vars.suffixes.uncertainty.attrs]
long_name = " uncertainty"
standard_name = "_uncertainty"

[vars.suffixes.detection_limit]
name = "_dl"
dtype = "dl_type_t"

[vars.suffixes.detection_limit.attrs]
long_name = " detection limit"
standard_name = "_detection_limit"

[vars.suffixes.volume]
name = "_vol"
dtype = "f4"

[vars.suffixes.volume.attrs]
long_name = " volume"
standard_name = "_volume"

[vars.suffixes.filtered]
name = "_filt"
dtype = "filt_type_t"

[vars.suffixes.filtered.attrs]
long_name = " filtered"
standard_name = "_filtered"

[vars.suffixes.counting_method]
name = "_counmet"
dtype = "counmet_type_t"

[vars.suffixes.counting_method.attrs]
long_name = " counting method"
standard_name = "_counting_method"

[vars.suffixes.unit]
name = "_unit"
dtype = "unit_type_t"

[vars.suffixes.unit.attrs]
long_name = " unit"
standard_name = "_unit"

[[enums]]
name = "bio_group_t"
fname = "dbo_biogroup.xlsx"
key = "biogroup"
value = "biogroup_id"

[[enums]]
name = "body_part_t"
fname = "dbo_bodypar.xlsx"
key = "bodypar"
value = "bodypar_id"

[[enums]]
name = "species_t"
fname = "dbo_species.xlsx"
key = "species"
value = "species_id"

[[enums]]
name = "sed_type_t"
fname = "dbo_sedtype.xlsx"
key = "sedtype"
value = "sedtype_id"

[[enums]]
name = "dl_type_t"
fname = "dbo_detection.xlsx"
key = "detection_name"
value = "detection_id"

[[enums]]
name = "unit_type_t"
fname = "dbo_unit.xlsx"
key = "unit_sanitized"
value = "unit_id"

[[enums]]
name = "dl_type_t"
fname = "dbo_detectlimit.xlsx"
key = "name_sanitized"
value = "id"

[[enums]]
name = "filt_type_t"
fname = "dbo_filtered.xlsx"
key = "name"
value = "id"

[[enums]]
name = "counmet_type_t"
fname = "dbo_counmet.xlsx"
key = "counmet"
value = "counmet_id"
